apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edgex-system
resources:
  - core.yaml
  - gateway.yaml
  - metadata.yaml

configMapGenerator:
  - name: edgex-metadata-contract
    files:
      - metadata-contract.json=config/metadata-contract.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: edgex-metadata-bootstrap
    app.kubernetes.io/part-of: edgex-system
