apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - overlays/testbed/server2
  - base/edge-namespace
  - base/device-serial-jetson
  - base/device-sensehat-raspi
  - base/device-discovery-agent
  - crds
  - base/adapter-controller
