apiVersion: v1
kind: ServiceAccount
metadata:
  name: edgex-adapter-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edgex-adapter-controller
rules:
  - apiGroups:
      - edgeai.etri.re.kr
    resources:
      - adapterruntimes
      - adapterruntimes/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edgex-adapter-controller
subjects:
  - kind: ServiceAccount
    name: edgex-adapter-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edgex-adapter-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgex-adapter-controller-node-reader
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edgex-adapter-controller-node-reader
subjects:
  - kind: ServiceAccount
    name: edgex-adapter-controller
    namespace: edgex-edge
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edgex-adapter-controller-node-reader
