apiVersion: v1
kind: Namespace
metadata:
  name: edgex-edge
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: edgex-edge-default-deny
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
