apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-registry-db
spec:
  template:
    spec:
      nodeSelector:
        environment: cloud
        kubernetes.io/arch: amd64
      containers:
        - name: db-container
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
