apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow-hub-eval

resources:
  - namespace.yaml
  - https://github.com/kubeflow/hub/manifests/kustomize/overlays/db?ref=v0.3.14

patches:
  - path: delete-upstream-secret.yaml
  - path: remove-empty-password.yaml
  - path: database-deployment.yaml
  - path: registry-deployment.yaml
  - path: metadata-pvc.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: edge-ai-model-platform
      app.kubernetes.io/managed-by: qualification-kustomize
      edgeai.etri.re.kr/qualification: kubeflow-hub
    includeSelectors: true
