apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edgex-edge
resources:
  - workload.yaml
configMapGenerator:
  - name: device-sensehat-raspi-config
    files:
      - configuration.yaml=config/configuration.yaml
      - etri-sensehat-temperature.yaml=config/etri-sensehat-temperature.yaml
      - etri-sensehat-humidity.yaml=config/etri-sensehat-humidity.yaml
      - etri-sensehat-pressure.yaml=config/etri-sensehat-pressure.yaml
      - etri-sensehat-compass.yaml=config/etri-sensehat-compass.yaml
      - etri-sensehat-orientation.yaml=config/etri-sensehat-orientation.yaml
      - etri-sensehat-gyroscope.yaml=config/etri-sensehat-gyroscope.yaml
      - sensehat-virtual-devices.yaml=config/sensehat-virtual-devices.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: device-sensehat-raspi
    app.kubernetes.io/part-of: edgex-system
