const test=require('node:test');
const assert=require('node:assert/strict');
global.NexusData=require('../app/static/nexus/live-data.js');
const O=require('../app/static/nexus/overview.js');
const now=Date.parse('2026-09-08T08:00:00Z');
const stamp=new Date(now).toISOString();
const entry=data=>({data,status:'ready',receivedAt:now,error:null});
function fixture(){return {services:entry({services:[{service_id:'one',display_name:'서비스',mode:'live',execution_ownership:{enabled:true,lease_valid:false,effective_mode:'STANDBY'}}]}),resources:entry([{node:'edge',kubernetesReady:true,utilization:{observedAt:stamp,cpuRatio:0,memoryRatio:.7,gpuRatio:null}}]),devices:entry([{name:'x',physical_device_id:'physical'},{name:'y',physical_device_id:'physical'},{name:'unassigned'}]),twins:entry({twins:[]}),operations:entry({generated_at:stamp,sources:{demo:{status:'observed'}},issues:[{reason:'execution_lease_expired'}],events:[],services:[{service_id:'one',observation_state:'Observed',quality:{valid:true,sample_count:10,observed_at:stamp,processing_latency_p95_ms:12}}]})};}
test('counts EdgeX registrations separately from physical sources; Ready does not imply active AI',()=>{const m=O.model(fixture(),now);assert.equal(m.devices.length,3);assert.equal(m.groups.length,1);assert.equal(m.nodeCounts.ready,1);assert.equal(m.execution(m.services[0]),'STANDBY');assert.equal(m.issues.length,1);});
test('real zero usage is retained; missing, expired, future and out-of-range measurements are unknown',()=>{const e=fixture();assert.equal(O.model(e,now).usage[0].cpuRatio,0);assert.equal(O.model(e,now).usage[0].gpuRatio,null);e.resources.data[0].utilization.cpuRatio=1.1;assert.equal(O.model(e,now).usage[0].cpuRatio,null);e.resources.data[0].utilization.observedAt=new Date(now-61000).toISOString();assert.equal(O.model(e,now).usage[0].memoryRatio,null);e.resources.data[0].utilization.observedAt=new Date(now+10000).toISOString();assert.equal(O.model(e,now).usage[0].memoryRatio,null);});
test('stale or failed responses never retain healthy node and issue claims',()=>{const e=fixture();e.resources.status='error';e.operations.status='error';const m=O.model(e,now);assert.equal(m.nodeCounts.ready,0);assert.equal(m.nodeCounts.unknown,1);assert.equal(m.usage[0].cpuRatio,null);assert.equal(m.demoCurrent,false);assert.deepEqual(m.issues,[]);assert.equal(m.latency[0].value,null);});
test('p95 requires current source and valid positive sample count, never fabricated zero',()=>{const e=fixture();assert.equal(O.model(e,now).latency[0].value,12);const q=e.operations.data.services[0].quality;q.valid=false;assert.equal(O.model(e,now).latency[0].value,null);q.valid=true;q.sample_count=0;q.processing_latency_p95_ms=0;assert.equal(O.model(e,now).latency[0].value,null);q.sample_count=10;e.operations.data.sources.demo.status='unavailable';assert.equal(O.model(e,now).latency[0].value,null);});
test('an expired ACTIVE lease is not counted as active; missing ownership is unknown',()=>{const e=fixture();e.services.data.services[0].execution_ownership.effective_mode='ACTIVE';let m=O.model(e,now);assert.equal(m.execution(m.services[0]),null);delete e.services.data.services[0].execution_ownership;m=O.model(e,now);assert.equal(m.execution(m.services[0]),null);});
test('event ordering uses original event time and keeps invalid timestamps at the end',()=>{const e=fixture();e.operations.data.events=[{timestamp:'bad'},{timestamp:'2026-08-01Z'},{timestamp:stamp}];assert.equal(O.model(e,now).events[0].timestamp,stamp);});
