FROM --platform=$BUILDPLATFORM golang:1.23.12-alpine3.21 AS builder

ARG TARGETOS=linux
ARG TARGETARCH

WORKDIR /build
ENV GO111MODULE=on \
    GOPROXY=https://goproxy.cn,direct

COPY api ./api
COPY mapper-framework ./mapper-framework
COPY mqttvirtual ./mqttvirtual

WORKDIR /build/mqttvirtual
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o main cmd/main.go


FROM ubuntu:18.04

COPY --from=builder /build/mqttvirtual/main /kubeedge/main
COPY --from=builder /build/mqttvirtual/config.yaml /kubeedge/config.yaml

WORKDIR /kubeedge
