apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - yamls/kube-flannel-common.yml
  - config/flannel-interfaces.yaml
  - yamls/kube-flannel-cloud.yml
  - yamls/kube-flannel-edge.yml
