apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../k8s

patches:
  - path: approved-routing-patch.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: sensor-anomaly-demo-network
    patch: |-
      - op: add
        path: /spec/egress/-
        value:
          to:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/name: sensor-anomaly-inference-server1
          ports:
            - protocol: TCP
              port: 8080
