apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../jetson/smoke
namespace: jetson-nano-gpu-smoke
patches:
  - target:
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/name
        value: jetson-nano-gpu-smoke
  - target:
      kind: Pod
    patch: |-
      - op: replace
        path: /spec/nodeSelector/kubernetes.io~1hostname
        value: etri-dev0001-jetorn
