apiVersion: v1
kind: ConfigMap
metadata:
  name: mqttvirtual-config
  namespace: default
data:
  configData: |
    grpc_server:
      socket_path: /etc/kubeedge/mqttvirtual.sock
    common:
      name: Mqttvirtual-mapper
      version: v1.13.0
      api_version: v1.0.0
      protocol: mqttvirtual
      address: 127.0.0.1
      edgecore_sock: /etc/kubeedge/dmi.sock
