apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mqttvirtual-mapper
  namespace: default
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mqttvirtual-mapper
  template:
    metadata:
      labels:
        app: mqttvirtual-mapper
    spec:
      nodeSelector:
        environment: edge
        edge.device/mapper: mqttvirtual
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: mqttvirtual
          volumeMounts:
            - name: kubeedge
              mountPath: /etc/kubeedge
            - name: config
              mountPath: /tmp
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-token
                  key: token
            - name: DEVICE_STATUS_FLUSH_SECONDS
              value: "30"
            - name: DEVICE_STATUS_JITTER_SECONDS
              value: "10"
            - name: DEVICE_STATUS_HEARTBEAT_SECONDS
              value: "120"
            - name: DEVICE_STATES_REPORT_ENABLED
              value: "false"
          image: 192.168.0.56:5000/mqttvirtual:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          command: [ "/bin/sh","-c" ]
          args:
            - rm -f /etc/kubeedge/mqttvirtual.sock && /kubeedge/main --config-file /tmp/config.yaml --v 4
      volumes:
        - name: kubeedge
          hostPath:
            path: /etc/kubeedge
            type: Directory
        - name: config
          configMap:
            name: mqttvirtual-config
            items:
              - key: configData
                path: config.yaml
