apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edgex-edge
resources:
  - workload.yaml
configMapGenerator:
  - name: device-serial-jetson-config
    files:
      - configuration.yaml=config/configuration.yaml
      - etri-arduino-serial.yaml=config/etri-arduino-serial.yaml
      - arduino-001.yaml=config/arduino-001.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: device-serial-jetson
    app.kubernetes.io/part-of: edgex-system
