apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-orch-state-aggregator
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: state-aggregator=192.168.0.56:5000/state-aggregator
    argocd-image-updater.argoproj.io/state-aggregator.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dsa04156/edge-ai-workspace.git'
    path: edge-orch/state-aggregator/k8s
    targetRevision: main
    kustomize: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-orch-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dsa04156/edge-ai-workspace.git'
    path: edge-orch/redis/k8s
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-orch-nvidia-device-plugin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dsa04156/edge-ai-workspace.git'
    path: edge-orch/nvidia-device-plugin/k8s
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
