apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-orch-state-aggregator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dsa04156/edge-ai-workspace.git'
    path: edge-orch/state-aggregator/k8s
    targetRevision: main
    kustomize: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-orch-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dsa04156/edge-ai-workspace.git'
    path: edge-orch/redis/k8s
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-orch-nvidia-device-plugin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dsa04156/edge-ai-workspace.git'
    path: edge-orch/nvidia-device-plugin/k8s
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-orch-mqttvirtual-mapper
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dsa04156/edge-ai-workspace.git'
    path: mappers/mqttvirtual/resource
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
