apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-orch-sensor-anomaly-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dsa04156/edge-ai-workspace.git
    path: edge-orch/sensor-anomaly-demo/k8s
    targetRevision: agent/edgex-central-docs
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: edgex-edge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
