# Sense HAT v1 settings for etri-dev0003-raspi5.
IMUType=6
FusionType=2
BusIsI2C=true
I2CBus=1
I2CSlaveAddress=106
AxisRotation=0

PressureType=3
I2CPressureAddress=92
HumidityType=2
I2CHumidityAddress=95

CompassCalValid=true
CompassCalMinX=-26.074535
CompassCalMinY=-2.034567
CompassCalMinZ=-14.253133
CompassCalMaxX=49.599648
CompassCalMaxY=70.567223
CompassCalMaxZ=55.166424
compassAdjDeclination=0.000000

compassCalEllipsoidValid=true
compassCalOffsetX=0.268940
compassCalOffsetY=0.530345
compassCalOffsetZ=-0.120908
compassCalCorr11=0.973294
compassCalCorr12=-0.014069
compassCalCorr13=-0.021423
compassCalCorr21=-0.014069
compassCalCorr22=0.965692
compassCalCorr23=-0.002746
compassCalCorr31=-0.021423
compassCalCorr32=-0.002746
compassCalCorr33=0.980103

AccelCalValid=true
AccelCalMinX=-0.988512
AccelCalMinY=-1.011500
AccelCalMinZ=-1.012328
AccelCalMaxX=1.006410
AccelCalMaxY=1.004973
AccelCalMaxZ=1.001244

GyroBiasValid=true
GyroBiasX=0.024642
GyroBiasY=0.020255
GyroBiasZ=-0.011905

LSM9DS1GyroSampleRate=2
LSM9DS1GyroFsr=1
LSM9DS1GyroHpf=4
LSM9DS1GyroBW=1
LSM9DS1AccelSampleRate=3
LSM9DS1AccelFsr=3
LSM9DS1AccelLpf=3
LSM9DS1CompassSampleRate=5
LSM9DS1CompassFsr=0
