apiVersion: devices.kubeedge.io/v1beta1
kind: Device
metadata:
  name: temp-device-01
  namespace: default
spec:
  deviceModelRef:
    name: virtual-temp-model
  nodeName: etri-dev0001-jetorn

  properties:
    - name: temperature
      collectCycle: 60000
      reportCycle: 60000
      reportToCloud: false
      visitors:
        protocolName: mqttvirtual
        configData:
          dataType: string
          jsonKey: temperature

    - name: sampling_interval
      collectCycle: 60000
      reportCycle: 60000
      reportToCloud: true
      visitors:
        protocolName: mqttvirtual
        configData:
          dataType: string
          jsonKey: sampling_interval

  protocol:
    protocolName: mqttvirtual
    configData:
      broker: tcp://127.0.0.1:1883
      subTopic: factory/devices/temp-device-01/telemetry
      pubTopic: factory/devices/temp-device-01/command
      clientID: temp-device-01-client
      username: ""
      password: ""
      qos: 1
