apiVersion: devices.kubeedge.io/v1beta1
kind: DeviceModel
metadata:
  name: virtual-vib-model
  namespace: default
spec:
  protocol: mqttvirtual
  properties:
    - name: vibration
      description: virtual vibration
      type: STRING
      accessMode: ReadOnly
    - name: alarm
      description: vibration alarm state
      type: STRING
      accessMode: ReadOnly
    - name: sampling_interval
      description: report interval
      type: STRING
      accessMode: ReadWrite
