apiVersion: devices.kubeedge.io/v1beta1
kind: DeviceModel
metadata:
  name: virtual-act-model
  namespace: default
spec:
  protocol: mqttvirtual
  properties:
    - name: power
      description: virtual power state
      type: STRING
      accessMode: ReadOnly
    - name: mode
      description: virtual actuator mode
      type: STRING
      accessMode: ReadOnly
    - name: sampling_interval
      description: report interval
      type: STRING
      accessMode: ReadWrite
