apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: edgex-edge

resources:
  - ../../../base/device-discovery-agent

patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: edge-device-discovery
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: edge-device-discovery
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: edge-device-discovery-i2c
    patch: |-
      - op: replace
        path: /spec/template/spec/nodeSelector/kubernetes.io~1hostname
        value: etri-dev0003-raspi5
