apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: edgex-edge

resources:
  - ../../../base/device-discovery-agent

patches:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: edge-device-discovery
    patch: |-
      - op: replace
        path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchExpressions/0/values
        value:
          - etri-dev0003-raspi5
